Authentication: Feature/members only
diazgio/Members-Only-project pull request #1
Opened 2020-10-15 17:24 UTC by diazgio

### Members Only

in this project we:
- Created Authentication Web app
- Add Linters.
- Add Gems from Ruby like Bundle, bootstrap, Simple_form, Hirb, Devise.
- Add an association between the tweet and the user models
- Add basic OOP

2020-10-15 20:00 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

### But in order to get it approved, we need to work on some changes. Let's see...

_Please go through my comments below._

Your project looks absolutely fantastic. Just make the changes suggested below and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-10-15 20:00 UTC, tirthajyoti-ghosh commented on config/routes.rb
> +  resources :posts
Please only declare routes that are required for this project - `:new`, `:create` and `:index`. Please include these and remove the others.

([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

2020-10-15 20:00 UTC, tirthajyoti-ghosh commented on app/controllers/posts_controller.rb
> +  before_action :authenticate_user!, except: %i[index show]
Please make use of a custom user login validation method instead of `authenticate_user!` provided by `devise`.
Declare this custom method in your ApplicationController ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)).
Remember to restrict the `before_action` to "only" `:new` and `:create` actions.

You can use something like this:

```ruby
# in apps/controllers/application_controller.rb

# must be a helper method to be used in views
helper_method :signed_in?

def signed_in?
  !current_user.nil?
end

# in apps/controllers/posts_controller.rb

before_action :signed_in_only!, only: [:new, :create]
.
.
.
private

def signed_in_only!
  redirect_to new_user_session_path unless signed_in?
end
```

2020-10-15 20:00 UTC, tirthajyoti-ghosh commented on app/views/layouts/application.html.erb
> +    <% end %>
Please remove all logic from your views. There should be absolutely no logic in views. Instead, use helper methods to outsource view logic.


 >Views are only for displaying information that became available to it from its corresponding controller not generating it.

**Resources** 
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
- [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

I have only pointed out here but it applies all the view logic.

2020-10-15 21:36 UTC, diazgio commented on app/views/layouts/application.html.erb
> +    <% end %>
Hello, thanks for the comments I already fix the two first but for this, but for this one I don't have any idea how to do it, I'll be so grateful if You tell how can I remove this flash notices into a helper method.

2020-10-15 22:26 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Lets work on the last requirement as stipulated by previous TSE's.
### [OPTIONAL]
- [ ] You could use this article as a guide https://stackoverflow.com/questions/12345065/rails-flash-message-helper
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-10-19 17:03 UTC, Dandush03 requested changes
# Status: :red_circle: Require Changes :red_circle: 
### Great Job! you did great applying changes, check out my comments below before submitting a new review.

- [ ] **Fix linter errors before submiting a review, and make sure they've all pass**

- [ ] __There shall be no logic in views.__
Please understand it's a hard requirement, I've seen that it was mentioned in previews review and the issue still stand. so i recomend the fallowing, open each view in any text editor and sarch for the word __`if`__ where ever you find it, move that logic to the helper. if you need some extra help with this issue you can request a 1 on 1 meeting with a Full Time TSE
> [Request 1 on 1 with a Full Time TSE](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-)
or contact me throught slack :wink: I will gladly guide you toward your next review

# Happy Coding :nerd_face: :computer:

2020-10-19 17:03 UTC, Dandush03 commented on config/routes.rb
> +  root to: 'posts#index'
- [ ] Please make sure to add the __`only/except`__ flag
> Check out [this docs](https://guides.rubyonrails.org/routing.html#configuring-the-rails-router), on how to do it

2020-10-20 00:06 UTC, diazgio commented
I manage to fix the routes issues, create a helper method for the flash notice and alerts, but I see all the projects from my partners and they have the same logic With the "If's", in the Twitter clone project teach us to create this kind of project and this is my baseline to build my project so I don't think that for now, it's necessary to remove all of them.

2020-10-20 01:01 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @diazgio :balloon: 

### Thank you for working on the changes requested by the previous reviewers :medal_sports: your project works well, :star:  and it has a great design claps to you for taking the time because both your project and repository look very professional :clap: :clap: :clap: that being said let's work on the following changes :construction: :construction_worker: 

#### Extra features
> Deleting users accounts were not in the scope of the project so you can either disable this action or make it work (if you decide to keep it I suggest you look into how to cascade delete records that belong to a deleted record from another entity using Rails) 

- [ ] This error happens whenever a user that has a post is deleted and you try to log in with a different user let's fix it

![image](https://user-images.githubusercontent.com/52209067/96526787-d3c1dc80-123b-11eb-88bb-0145cb92357b.png)

#### [OPTIONAL]

##### No Logic or Complexity in views or partials
> I see you've decided not to do this change because it was requested as optional, but actually, this is a mandatory request for all rails projects that have views, I'm very sorry it wasn't requested by the first reviewer. If you decide to work on it [here's ](https://www.toptal.com/ruby-on-rails/top-10-mistakes-that-rails-programmers-make#common-mistake-2-putting-too-much-logic-in-the-view)an article that has a straight forward example on how to do it.

* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There should be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright 

### That's it! :raised_hands: 

### Please :pray:  do the changes :technologist: and submit back for a code review when you are done :memo: 

### Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-10-20 21:40 UTC, maelfosso approved these changes
# Congratulations :clap:

Thank you for making the suggested changes :+1: , You can merge it now :satisfied: 

Good continuation :handshake: 

Mael FOSSO

2020-10-20 21:40 UTC, merged